# Generated by Django 5.0.4 on 2024-05-05 19:36

import django.core.validators
import django.db.models.deletion
import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(default=recipe.models.generate_unique_code, editable=False, max_length=7, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('on_time_delivery_rate', models.FloatField(null=True, verbose_name='On Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(null=True, verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(null=True, verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(null=True, verbose_name='Fulfillment Rate')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default=recipe.models.generate_unique_code, editable=False, max_length=7, unique=True)),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='draft', max_length=10)),
                ('quality_rating', models.FloatField(default=None, null=True, verbose_name='')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('acknowledgement_date', models.DateTimeField(null=True)),
                ('actual_delivery_date', models.DateTimeField(null=True)),
                ('vendor_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('on_time_delivery_rate', models.FloatField(null=True)),
                ('quality_rating_avg', models.FloatField(null=True)),
                ('average_response_time', models.FloatField(null=True)),
                ('fulfillment_rate', models.FloatField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
